### ISSUE TITLE
Reward

### ISSUE THREAD

**Issue by Miminlaili** [PayString/paystring#773]
## Bonus

**Are you willing to submit a pull request to implement this change?**

**Comment by BigBlueHundids** [comment]
>.

**Comment by BigBlueHundids** [comment]
> ## Detailed Description
> ## Context
> ## Possible Implementation
> ### Alternatives Considered
> ## Additional Context
> ## Bonus
> **Are you willing to submit a pull request to implement this change?**

**Comment by BigBlueHundids** [comment]
>.
